[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
testing-derive = { path = "derive" }
x86_64.workspace = true
log.workspace = true
linkme.workspace = true
thiserror.workspace = true